import * as RDF from "rdf-js";
declare type Rotation = SPO | POS | OSP;
declare type SPO = ["subject", "predicate", "object"];
declare type POS = ["predicate", "object", "subject"];
declare type OSP = ["object", "subject", "predicate"];
declare const SPO: SPO;
declare const POS: POS;
declare const OSP: OSP;
declare type Index = Map<number, Map<number, Set<number>>>;
export default class Store {
    #private;
    constructor(quads?: RDF.Quad[], options?: {
        factory?: RDF.DataFactory;
    });
    get size(): number;
    private addToIndex;
    private removeFromIndex;
    generateIndex(index0: Index, key0: number | null, key1: number | null, key2: number | null, rotation: Rotation, graph: string): Generator<RDF.Quad, void>;
    generateIndex1(e: [string, string, string], index1: Map<number, Set<number>>, key1: number | null, key2: number | null, r: Rotation, graph: string): Generator<RDF.Quad, void>;
    generateIndex2(e: [string, string, string], key2: number | null, index2: Set<number>, r: Rotation, graph: string): Generator<RDF.Quad, void>;
    private makeQuad;
    private loopByKey0;
    private loopByKey1;
    private loopBy2Keys;
    private countInIndex;
    private countInIndex1;
    private getGraphIndices;
    private getGraphIndex;
    addQuad(quad: RDF.Quad): void;
    addQuad(subject: RDF.Term, predicate: RDF.Term, object: RDF.Term, graph?: RDF.Term): void;
    addQuads(quads: RDF.Quad[]): void;
    removeQuad(quad: RDF.Quad): boolean;
    removeQuad(subject: RDF.Term, predicate: RDF.Term, object: RDF.Term, graph?: RDF.Term): boolean;
    remove(stream: IterableIterator<RDF.Quad>): void;
    removeMatches(subject: RDF.Term | null, predicate: RDF.Term | null, object: RDF.Term | null, graph: RDF.Term | null): void;
    deleteGraph(graph: RDF.Term): void;
    private getIds;
    quads(subject: RDF.Term | null, predicate: RDF.Term | null, object: RDF.Term | null, graph: RDF.Term | null): Generator<RDF.Quad, void>;
    getQuads(subject: RDF.Term | string | null, predicate: RDF.Term | string | null, object: RDF.Term | string | null, graph: RDF.Term | string | null): RDF.Quad[];
    countQuads(subject: RDF.Term | null, predicate: RDF.Term | null, object: RDF.Term | null, graph: RDF.Term | null): number;
    getSubjects(predicate: RDF.Term | string | null, object: RDF.Term | string | null, graph: RDF.Term | string | null): RDF.Quad_Subject[];
    subjects(predicate: RDF.Term | null, object: RDF.Term | null, graph: RDF.Term | null): Generator<RDF.Quad_Subject, void, undefined>;
    getPredicates(subject: RDF.Term | string | null, object: RDF.Term | string | null, graph: RDF.Term | string | null): RDF.Quad_Predicate[];
    predicates(subject: RDF.Term | null, object: RDF.Term | null, graph: RDF.Term | null): Generator<RDF.Quad_Predicate, void, undefined>;
    getObjects(subject: RDF.Term | string | null, predicate: RDF.Term | string | null, graph: RDF.Term | string | null): RDF.Quad_Object[];
    private unique;
    objects(subject: RDF.Term | null, predicate: RDF.Term | null, graph: RDF.Term | null): Generator<RDF.Quad_Object, void, undefined>;
    getGraphs(subject: RDF.Term | string | null, predicate: RDF.Term | string | null, object: RDF.Term | string | null): RDF.Quad_Graph[];
    graphs(subject: RDF.Term | string | null, predicate: RDF.Term | string | null, object: RDF.Term | string | null): Generator<RDF.Quad_Graph>;
    createBlankNode(suggestedName: string): RDF.BlankNode;
}
export {};
